services:
  fastapi:
    container_name: template-api
    build:
      context: .
      dockerfile: dev.Dockerfile
    entrypoint: /opt/pysetup/app/entrypoint.sh
    env_file:
      - .env
    volumes:
      - ./app:/opt/pysetup/app
      - .env:/opt/pysetup/app/.env
    ports:
      - "8000:80"
    depends_on:
      - postgres
      - redis
    stop_grace_period: 3s

  postgres:
    image: postgres:17.4
    container_name: template-db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.4.2
    container_name: template-cache
    env_file:
      - .env
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
